spring:
  datasource:
    url: jdbc:mysql://${DB_MASTER_HOST:localhost}:${DB_MASTER_PORT:3306}/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: ${DB_MASTER_USERNAME:root}
    password: ${DB_MASTER_PASSWORD:root}
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
